// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOckPW5YhrP7re2-pmJSNJYxE6o9FdUao',
    appId: '1:718178402915:web:c8a10c925b11273e466e56',
    messagingSenderId: '718178402915',
    projectId: 'math-hw-auth',
    authDomain: 'math-hw-auth.firebaseapp.com',
    storageBucket: 'math-hw-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMUBVypyyyfu2BYPIKjv7kVXHJNSFrOE',
    appId: '1:718178402915:android:b86b9e7e3c5fa1b3466e56',
    messagingSenderId: '718178402915',
    projectId: 'math-hw-auth',
    storageBucket: 'math-hw-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXqOo7SUn9Vd8lB7v_E-huKWHPF-p_UP8',
    appId: '1:718178402915:ios:9beac8136ab90fa2466e56',
    messagingSenderId: '718178402915',
    projectId: 'math-hw-auth',
    storageBucket: 'math-hw-auth.firebasestorage.app',
    iosBundleId: 'com.example.mathHw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXqOo7SUn9Vd8lB7v_E-huKWHPF-p_UP8',
    appId: '1:718178402915:ios:9beac8136ab90fa2466e56',
    messagingSenderId: '718178402915',
    projectId: 'math-hw-auth',
    storageBucket: 'math-hw-auth.firebasestorage.app',
    iosBundleId: 'com.example.mathHw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOckPW5YhrP7re2-pmJSNJYxE6o9FdUao',
    appId: '1:718178402915:web:d40e717ba908031a466e56',
    messagingSenderId: '718178402915',
    projectId: 'math-hw-auth',
    authDomain: 'math-hw-auth.firebaseapp.com',
    storageBucket: 'math-hw-auth.firebasestorage.app',
  );
}
